[tools]
go = "1.26"
java = "graalvm-community-21"
python = "3.14.5"
"aqua:go-task/task" = "latest"
"npm:markdownlint-cli2" = "latest"
"pipx:yamllint" = "latest"
"aqua:golangci/golangci-lint" = "latest"

[env]
GOPATH = "{{config_root}}/.cache/go"

[settings]
experimental = true
